### ISSUE TITLE
Electronics fixes for v2.1

### ISSUE THREAD

**Issue by mryall-mawson** [mawson-rovers/hestia#28]
Things to tidy up:
* Footprints for inductor, diodes, etc.
* LED resistors - red & blue bright
* Update KiCAD
* Increase diameter/spacing of SW2

**Comment by JDMawson** [comment]
inductor footprint changed. diode footprint changed. Most of DRC issues resolved. Mawson Rovers logo and UTS logo need to be rereferenced from the Hestia footprint libraries but they seem to be different sizes from those in the libraries. Maybe the better solution is to create new library footprints from the logos already on the PCB. Smartsat and SpiralBlue logos seem to be only on the PCB and not referenced from libraries but are listed as footprint elements. Perhaps they can also be copied into footprint libraries and referenced. The logos should be given different footprint designator names.

**Comment by JDMawson** [comment]
i think I've finished shifting all the designators and adding text. DRC is satisfied.

**Comment by JDMawson** [comment]
having a look at the build artifacts. How are some components being excluded. i see most of the thruhole have been removed from the BOM but there is still one thruhole component present in the BOM. Would it be possible to create two BOM files - one for SMD and one for thruhole?

**Comment by mryall-mawson** [comment]
@JDMawson I had a look at the BOM config in the [hestia.kibot.yml](https://github.com/mawson-rovers/hestia/blob/main/hestia-pcb/hestia.kibot.yml) config file, and can't see any reason why THT components would be (mostly) excluded. I think manual export from KiCAD is probably easiest at this stage, and we can look into automating it as a later enhancement.

Closing this issue off as the original items have been fixed. Issue #38 covers the problem with the current measurement, and issue #35 covers the heater trace. I'll raise a new one for the actual fabrication too.
