### ISSUE TITLE
Add syslog option for output, remove any unnecessary logging

### ISSUE THREAD

**Issue by mryall-mawson** [mawson-rovers/hestia#67]
WS-1 needs us to log output to syslog, not stdout.

There is also quite a bit of logging if one of the boards is non-responsive. It filled up one of my Beaglebones here with 300MB of logs. We should fix that so it is one log message per attempt, instead of 10-12 lines.

**Comment by mryall-mawson** [comment]
I started some work on this on the `syslog` branch but didn't get around to testing it:

https://github.com/mawson-rovers/hestia/commit/6d1c36f965f9f69e89682a0ccbc926b81b5f9545

**Comment by cowen-mawson** [comment]
Splitting the syslog task from the reduce logging task which is now tracked at #70

**Comment by mryall-mawson** [comment]
Done - needs testing with USyd.
