### ISSUE TITLE
TVac testing scripts

### ISSUE THREAD

**Issue by mryall-mawson** [mawson-rovers/hestia#76]
Requirements:
* 2 tests required - one for each board
  * Low temperature hold at -10°C - run heat & cool cycle on top/bottom
* Not doing test at high temperature hold

Current testing process at CUAVA:
* `cd UTS`
* `uts-cli test`

Suggested interface for CUAVA:
* `uts-cli run programs/tvac1.toml` - bottom, temp_abort = 85, default settings otherwise
* `uts-cli run programs/tvac2.toml` - top, temp_abort = 85, default settings otherwise

Use existing functionality from uts-run (which loads from UTS_PROGRAM_FILE) to load from tvac-1.toml, tvac-2.toml, etc.

Need to run uts-log in the background, like we do with systemd on test BBB. Could use CubeOS scheduler? Or another way to run system services? Want to capture data before/after uts-cli execution.

Schedule for TVac:
* start `uts-log` as soon as possible after boot
* ensure log output going to `$UTS_LOG_PATH`
* run `uts-cli run tvac-1.toml`, etc. manually at specified times

**Comment by cowen-mawson** [comment]
From Nick:

> For the TVac test we’ll go for the following:
Full power test
Cut off temp, 85C (measured by TH1)
No high-temp test after all

**Comment by mryall-mawson** [comment]
Tested manually via `uts-cli run ...`, and works correctly.

Waiting for scheduler to be working on WS-1 to finalise this.

**Comment by mryall-mawson** [comment]
Scheduler is now working. Waiting to receive execution logs to confirm it is running the scripts properly.

**Comment by mryall-mawson** [comment]
Fully tested today with the scheduler. We ran both tvac1 and tvac2 schedules, and got the associated data back to UTS.

Some minor remaining issues for CUAVA to fix:
- File transfer fails with spurious error at the end, even though it was successful
- Processes started by the scheduler aren't terminated when the schedule is stopped
- Scheduler periodic tasks don't seem to run periodically (which we are now doing with the `zip` task).
